%YAML 1.2
%TAG !n! tag:nimyaml.org,2016:
--- !n!custom:MonitorConfig 
sleep: 1
targets: 
  - 
    name: Generate js
    paths: [src, tests]
    commands:
      - nimble build
    extensions: [.nim]
    files: []
    exclude_extensions: []
    exclude_files: []
    once: y
